<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU</Platforms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  <ItemGroup>
    <None Update="Resource\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MiracleGamesWin32">
      <HintPath>SDK\MiracleGamesWin32.dll</HintPath>
      <Private>True</Private>
      <DisableRuntimeHostConfiguration>True</DisableRuntimeHostConfiguration>
    </Reference>

    <Reference Include="RichTextBoxLinks">
      <HintPath>SDK\RichTextBoxLinks.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="AxInterop.WMPLib">
      <HintPath>SDK\AxInterop.WMPLib.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Interop.WMPLib">
      <HintPath>SDK\Interop.WMPLib.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Windows">
      <HintPath>SDK\Windows.winmd</HintPath>
      <IsWinMDFile>true</IsWinMDFile>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="SDK\resource\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SDK\runtimes\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SDK\x64\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SDK\x86\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>